# Generated by Django 4.2.16 on 2025-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('topic', models.CharField(default='Misc', max_length=128)),
                ('subject', models.CharField(default='Misc', max_length=128)),
                ('q_type', models.CharField(choices=[('MCQ', 'mcq'), ('Conceptual', 'conceptual'), ('Speed', 'speed')], max_length=16)),
                ('option1', models.CharField(max_length=256, null=True)),
                ('option2', models.CharField(max_length=256, null=True)),
                ('option3', models.CharField(max_length=256, null=True)),
                ('option4', models.CharField(max_length=256, null=True)),
                ('answer', models.CharField(max_length=512, null=True)),
                ('level', models.CharField(choices=[('Easy', 'easy'), ('Medium', 'medium'), ('Hard', 'hard')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('raw_score', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
