# Generated by Django 4.2.16 on 2025-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepdungeon', '0003_dailyevent_userprofile_userdailyquest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='Misc', max_length=128),
        ),
    ]
