# Generated by Django 4.2.16 on 2025-07-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepdungeon', '0003_alter_question_answer_alter_question_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=512),
        ),
    ]
