# Generated by Django 4.2.16 on 2025-07-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepdungeon', '0004_alter_question_answer_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=16),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('conceptual', 'Conceptual'), ('speed', 'Speed')], max_length=16),
        ),
    ]
