# Generated by Django 4.2.16 on 2025-07-12 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepdungeon', '0004_question_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('completed_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='prepdungeon.completedtest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prepdungeon.question')),
            ],
        ),
    ]
