# Generated by Django 4.2.16 on 2025-07-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepdungeon', '0005_completedtest_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtest',
            name='analysis',
            field=models.TextField(default='No analysis available'),
        ),
        migrations.AddField(
            model_name='completedtest',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='completedtest',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
