# Generated by Django 4.2.16 on 2025-07-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepdungeon', '0006_completedtest_analysis_completedtest_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stream',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
